package com.quanquan.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.quanquan.dao.ProvinceDao;
import com.quanquan.dao.CityDao;
import com.quanquan.dao.CometentDao;
import com.quanquan.dao.SchoolDao;
import com.quanquan.dao.UserStateDao;
import com.quanquan.dao.VocationDao;
import com.quanquan.dao.TodayRecommendDao;
import com.quanquan.dao.ConversationDao;
import com.quanquan.dao.FlipperDao;
import com.quanquan.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ProvinceDao.createTable(db, ifNotExists);
        CityDao.createTable(db, ifNotExists);
        CometentDao.createTable(db, ifNotExists);
        SchoolDao.createTable(db, ifNotExists);
        UserStateDao.createTable(db, ifNotExists);
        VocationDao.createTable(db, ifNotExists);
        TodayRecommendDao.createTable(db, ifNotExists);
        ConversationDao.createTable(db, ifNotExists);
        FlipperDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ProvinceDao.dropTable(db, ifExists);
        CityDao.dropTable(db, ifExists);
        CometentDao.dropTable(db, ifExists);
        SchoolDao.dropTable(db, ifExists);
        UserStateDao.dropTable(db, ifExists);
        VocationDao.dropTable(db, ifExists);
        TodayRecommendDao.dropTable(db, ifExists);
        ConversationDao.dropTable(db, ifExists);
        FlipperDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ProvinceDao.class);
        registerDaoClass(CityDao.class);
        registerDaoClass(CometentDao.class);
        registerDaoClass(SchoolDao.class);
        registerDaoClass(UserStateDao.class);
        registerDaoClass(VocationDao.class);
        registerDaoClass(TodayRecommendDao.class);
        registerDaoClass(ConversationDao.class);
        registerDaoClass(FlipperDao.class);
        registerDaoClass(UserDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
